// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG1EjvFPI83YN7WKiNITgZS9fWAFxyYIg',
    appId: '1:20060645538:android:9ffba85ac7da538ef84ffb',
    messagingSenderId: '20060645538',
    projectId: 'fikra-d0835',
    storageBucket: 'fikra-d0835.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSQIOdxMpkfaxpyA65KgXO8QTezkZ4MRs',
    appId: '1:20060645538:ios:552b4c6948abf3dcf84ffb',
    messagingSenderId: '20060645538',
    projectId: 'fikra-d0835',
    storageBucket: 'fikra-d0835.appspot.com',
    androidClientId: '20060645538-jsh7pskm0adk642qpesaahkq4bvoo09e.apps.googleusercontent.com',
    iosClientId: '20060645538-po1u8efbbh8erc35bfg936e73riusmur.apps.googleusercontent.com',
    iosBundleId: 'com.main.fikra',
  );
}
