// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRYHuZaWwsttH1AqX9KqTqcKTCtRMXPHg',
    appId: '1:1085291452706:web:8c344e6adc7360351ced7b',
    messagingSenderId: '1085291452706',
    projectId: 'fluttershare-74808',
    authDomain: 'fluttershare-74808.firebaseapp.com',
    storageBucket: 'fluttershare-74808.appspot.com',
    measurementId: 'G-YZ9KMSJQXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdPDnGVIw7krn0wCdLSloWykcubvDcCBU',
    appId: '1:1085291452706:android:ced6b63bc8cffd271ced7b',
    messagingSenderId: '1085291452706',
    projectId: 'fluttershare-74808',
    storageBucket: 'fluttershare-74808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPjTdlTgG5LfFTGkpHk8zvpUqrQD-Q-mM',
    appId: '1:1085291452706:ios:7ddf6e69de7fcf3e1ced7b',
    messagingSenderId: '1085291452706',
    projectId: 'fluttershare-74808',
    storageBucket: 'fluttershare-74808.appspot.com',
    iosBundleId: 'com.example.fluttershare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPjTdlTgG5LfFTGkpHk8zvpUqrQD-Q-mM',
    appId: '1:1085291452706:ios:b88de0cb758837fb1ced7b',
    messagingSenderId: '1085291452706',
    projectId: 'fluttershare-74808',
    storageBucket: 'fluttershare-74808.appspot.com',
    iosBundleId: 'com.example.fluttershare.RunnerTests',
  );
}
